# This is a basic workflow to help you get started with Actions

name: Node.js CD All

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.USERNAME }}/${{ github.ref_name }}/
          git pull origin ${{ github.ref_name }}
          git status
          npm install --only=prod
          if [ "${{ github.ref_name }}" = "main" ]; then
            pm2 describe backend >> /dev/null && pm2 restart backend || pm2 start npm --name "backend" -- run start
          elif [ "${{ github.ref_name }}" = "develop" ]; then
            pm2 describe backend >> /dev/null && pm2 restart backend || pm2 start npm --name "backend" -- run dev
          fi
